displayName: Query Parameter
type: middleware

import: github.com/SlothCroissant/traefik-queryparam-plugin

summary: Add configured query parameters to HTTP requests

testData:
  QueryParams:
    source: traefik
    environment: production
