displayName: QueryParamsPlugin
type: middleware

import: github.com/SlothCroissant/traefik-queryparam-plugin

summary: Add and remove configured query parameters from HTTP requests

testData:
  AddQueryParams:
    - key: source
      value: traefik
    - key: environment
      value: production
  RemoveQueryParams:
    - key: source
      value: client
    - key: temporary
