name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Semantic Versioning
        id: release
        uses: python-semantic-release/python-semantic-release@v10.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: "false"
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
      - name: Create Release
        if: steps.release.outputs.released == 'true'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.release.outputs.tag }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
