name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Determine release version
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v6
        with:
          semantic_version: 25.0.8
          branches: main
          extra_plugins: |
            @semantic-release/commit-analyzer@13.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub release
        if: steps.semantic-release.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v3.0.2
        with:
          tag_name: ${{ steps.semantic-release.outputs.new_release_git_tag }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
